// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'resource.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Resource _$ResourceFromJson(Map<String, dynamic> json) {
  return Resource(
    androidVersion: json['androidVersion'] as String,
    iosVersion: json['iosVersion'] as String,
    mobileAppStatus: json['mobileAppStatus'] as String,
    locationId: json['locationId'] as String,
    loginCount: json['loginCount'] as String,
    deviceAppVer: json['deviceAppVer'] as String,
    flatNumber: json['flatNumber'] as String,
    consumerName: json['consumerName'] as String,
    consumerMobileNo: json['consumerMobileNo'] as String,
    consumerEmailId: json['consumerEmailId'] as String,
    balanceAmount: json['balanceAmount'] as String,
    dgBalanceAmount: json['dgBalanceAmount'] as String,
    lastRechargeTime: json['lastRechargeTime'] as String,
    dgLastRechargeTime: json['dgLastRechargeTime'] as String,
    lastCouponNumber: json['lastCouponNumber'] as String,
    dgLastCouponNumber: json['dgLastCouponNumber'] as String,
    lastCouponAmount: json['lastCouponAmount'] as String,
    dgLastCouponAmount: json['dgLastCouponAmount'] as String,
    dgReading: json['dgReading'] as String,
    gridReading: json['gridReading'] as String,
    dgAmt: json['dgAmt'] as String,
    gridAmt: json['gridAmt'] as String,
    lastReadingUpdated: json['lastReadingUpdated'] as String,
    dgLastReadingUpdated: json['dgLastReadingUpdated'] as String,
    notificationEmail: json['notificationEmail'] as String,
    notificationSms: json['notificationSms'] as String,
    bpNo: json['bpNo'] as String,
    consumerNo: json['consumerNo'] as String,
    accountNo: json['accountNo'] as String,
    moveInDate: json['moveInDate'] as String,
    notificationIvrs: json['notificationIvrs'] as String,
    notificationAppLoad: json['notificationAppLoad'] as String,
    notificationAppBalance: json['notificationAppBalance'] as String,
    lowBalAlert: json['lowBalAlert'] as String,
    dgLowBalAlert: json['dgLowBalAlert'] as String,
    notificationAppEsource: json['notificationAppEsource'] as String,
    notificationAppUnitConsumption:
        json['notificationAppUnitConsumption'] as String,
    alertDailyConsumptionGrid: json['alertDailyConsumptionGrid'] as String,
    alertDailyConsumptionDg: json['alertDailyConsumptionDg'] as String,
    loadSettingEnabled: json['loadSettingEnabled'] as String,
    powerCutRestoreNotification: json['powerCutRestoreNotification'] as String,
    rechargeNotification: json['rechargeNotification'] as String,
    gridSanctionedLoad: json['gridSanctionedLoad'] as String,
    dgSanctionedLoad: json['dgSanctionedLoad'] as String,
    loadUnit: json['loadUnit'] as String,
    meterType: json['meterType'] as String,
    gridLoadAlarm: json['gridLoadAlarm'] as String,
    dgLoadAlarm: json['dgLoadAlarm'] as String,
    gridOverloadSetting: json['gridOverloadSetting'] as String,
    dgOverloadSetting: json['dgOverloadSetting'] as String,
    gridOverloadFromTime: json['gridOverloadFromTime'] as String,
    gridOverloadToTime: json['gridOverloadToTime'] as String,
    dgOverloadFromTime: json['dgOverloadFromTime'] as String,
    dgOverloadToTime: json['dgOverloadToTime'] as String,
    overloadGrid: json['overloadGrid'] as String,
    overloadDg: json['overloadDg'] as String,
    siteId: json['siteId'] as String,
    siteName: json['siteName'] as String,
    siteAddress: json['siteAddress'] as String,
    siteCity: json['siteCity'] as String,
    siteState: json['siteState'] as String,
    siteCountry: json['siteCountry'] as String,
    siteZipcode: json['siteZipcode'] as String,
    siteSupervisorName: json['siteSupervisorName'] as String,
    siteSupervisorContactNo: json['siteSupervisorContactNo'] as String,
    siteSupervisorEmailId: json['siteSupervisorEmailId'] as String,
    siteSupportConcernName: json['siteSupportConcernName'] as String,
    siteSupportContactNo: json['siteSupportContactNo'] as String,
    siteSupportEmailId: json['siteSupportEmailId'] as String,
    mainLicense: json['mainLicense'] as String,
    application: json['application'] as String,
    readingUnit: json['readingUnit'] as String,
    currency: json['currency'] as String,
    siteCode: json['siteCode'] as String,
    balanceEnable: json['balanceEnable'] as String,
    readingEnable: json['readingEnable'] as String,
    monthlyBillEnable: json['monthlyBillEnable'] as String,
    monthlyBillNoOfMonth: json['monthlyBillNoOfMonth'] as String,
    pLM: json['pLM'] as String,
    pgEnablePaytm: json['pgEnablePaytm'] as String,
    pgEnableMobikwik: json['pgEnableMobikwik'] as String,
    paytmMobileUrl: json['paytmMobileUrl'] as String,
    mobikwikMobileUrl: json['mobikwikMobileUrl'] as String,
    pgEnableHdfc: json['pgEnableHdfc'] as String,
    paytmImage: json['paytmImage'] as String,
    rechargePopupMessage: json['rechargePopupMessage'] as String,
    energySource: json['energySource'] as String,
    lastReadingUpdatedDg: json['lastReadingUpdatedDg'] as String,
    displayLoadSettingScreen: json['displayLoadSettingScreen'] as String,
    dailyDgUnit: json['dailyDgUnit'] as int,
    dailyGridUnit: json['dailyGridUnit'] as int,
    monthlyDgUnit: json['monthlyDgUnit'] as int,
    monthlyGridUnit: json['monthlyGridUnit'] as int,
    dailyDgAmount: json['dailyDgAmount'] as int,
    dailyGridAmount: json['dailyGridAmount'] as int,
    monthlyDgAmount: json['monthlyDgAmount'] as int,
    monthlyGridAmount: (json['monthlyGridAmount'] as num)?.toDouble(),
    fixCharges: json['fixCharges'] as int,
    drCr: json['drCr'] as String,
    fixChargesMonthly: json['fixChargesMonthly'] as int,
    drCrMonthly: json['drCrMonthly'] as String,
    dgFixChargesMonthly: json['dgFixChargesMonthly'] as int,
    dgDrCrMonthly: json['dgDrCrMonthly'] as String,
  );
}

Map<String, dynamic> _$ResourceToJson(Resource instance) => <String, dynamic>{
      'androidVersion': instance.androidVersion,
      'iosVersion': instance.iosVersion,
      'mobileAppStatus': instance.mobileAppStatus,
      'locationId': instance.locationId,
      'loginCount': instance.loginCount,
      'deviceAppVer': instance.deviceAppVer,
      'flatNumber': instance.flatNumber,
      'consumerName': instance.consumerName,
      'consumerMobileNo': instance.consumerMobileNo,
      'consumerEmailId': instance.consumerEmailId,
      'balanceAmount': instance.balanceAmount,
      'dgBalanceAmount': instance.dgBalanceAmount,
      'lastRechargeTime': instance.lastRechargeTime,
      'dgLastRechargeTime': instance.dgLastRechargeTime,
      'lastCouponNumber': instance.lastCouponNumber,
      'dgLastCouponNumber': instance.dgLastCouponNumber,
      'lastCouponAmount': instance.lastCouponAmount,
      'dgLastCouponAmount': instance.dgLastCouponAmount,
      'dgReading': instance.dgReading,
      'gridReading': instance.gridReading,
      'dgAmt': instance.dgAmt,
      'gridAmt': instance.gridAmt,
      'lastReadingUpdated': instance.lastReadingUpdated,
      'dgLastReadingUpdated': instance.dgLastReadingUpdated,
      'notificationEmail': instance.notificationEmail,
      'notificationSms': instance.notificationSms,
      'bpNo': instance.bpNo,
      'consumerNo': instance.consumerNo,
      'accountNo': instance.accountNo,
      'moveInDate': instance.moveInDate,
      'notificationIvrs': instance.notificationIvrs,
      'notificationAppLoad': instance.notificationAppLoad,
      'notificationAppBalance': instance.notificationAppBalance,
      'lowBalAlert': instance.lowBalAlert,
      'dgLowBalAlert': instance.dgLowBalAlert,
      'notificationAppEsource': instance.notificationAppEsource,
      'notificationAppUnitConsumption': instance.notificationAppUnitConsumption,
      'alertDailyConsumptionGrid': instance.alertDailyConsumptionGrid,
      'alertDailyConsumptionDg': instance.alertDailyConsumptionDg,
      'loadSettingEnabled': instance.loadSettingEnabled,
      'powerCutRestoreNotification': instance.powerCutRestoreNotification,
      'rechargeNotification': instance.rechargeNotification,
      'gridSanctionedLoad': instance.gridSanctionedLoad,
      'dgSanctionedLoad': instance.dgSanctionedLoad,
      'loadUnit': instance.loadUnit,
      'meterType': instance.meterType,
      'gridLoadAlarm': instance.gridLoadAlarm,
      'dgLoadAlarm': instance.dgLoadAlarm,
      'gridOverloadSetting': instance.gridOverloadSetting,
      'dgOverloadSetting': instance.dgOverloadSetting,
      'gridOverloadFromTime': instance.gridOverloadFromTime,
      'gridOverloadToTime': instance.gridOverloadToTime,
      'dgOverloadFromTime': instance.dgOverloadFromTime,
      'dgOverloadToTime': instance.dgOverloadToTime,
      'overloadGrid': instance.overloadGrid,
      'overloadDg': instance.overloadDg,
      'siteId': instance.siteId,
      'siteName': instance.siteName,
      'siteAddress': instance.siteAddress,
      'siteCity': instance.siteCity,
      'siteState': instance.siteState,
      'siteCountry': instance.siteCountry,
      'siteZipcode': instance.siteZipcode,
      'siteSupervisorName': instance.siteSupervisorName,
      'siteSupervisorContactNo': instance.siteSupervisorContactNo,
      'siteSupervisorEmailId': instance.siteSupervisorEmailId,
      'siteSupportConcernName': instance.siteSupportConcernName,
      'siteSupportContactNo': instance.siteSupportContactNo,
      'siteSupportEmailId': instance.siteSupportEmailId,
      'mainLicense': instance.mainLicense,
      'application': instance.application,
      'readingUnit': instance.readingUnit,
      'currency': instance.currency,
      'siteCode': instance.siteCode,
      'balanceEnable': instance.balanceEnable,
      'readingEnable': instance.readingEnable,
      'monthlyBillEnable': instance.monthlyBillEnable,
      'monthlyBillNoOfMonth': instance.monthlyBillNoOfMonth,
      'pLM': instance.pLM,
      'pgEnablePaytm': instance.pgEnablePaytm,
      'pgEnableMobikwik': instance.pgEnableMobikwik,
      'paytmMobileUrl': instance.paytmMobileUrl,
      'mobikwikMobileUrl': instance.mobikwikMobileUrl,
      'pgEnableHdfc': instance.pgEnableHdfc,
      'paytmImage': instance.paytmImage,
      'rechargePopupMessage': instance.rechargePopupMessage,
      'energySource': instance.energySource,
      'lastReadingUpdatedDg': instance.lastReadingUpdatedDg,
      'displayLoadSettingScreen': instance.displayLoadSettingScreen,
      'dailyDgUnit': instance.dailyDgUnit,
      'dailyGridUnit': instance.dailyGridUnit,
      'monthlyDgUnit': instance.monthlyDgUnit,
      'monthlyGridUnit': instance.monthlyGridUnit,
      'dailyDgAmount': instance.dailyDgAmount,
      'dailyGridAmount': instance.dailyGridAmount,
      'monthlyDgAmount': instance.monthlyDgAmount,
      'monthlyGridAmount': instance.monthlyGridAmount,
      'fixCharges': instance.fixCharges,
      'drCr': instance.drCr,
      'fixChargesMonthly': instance.fixChargesMonthly,
      'drCrMonthly': instance.drCrMonthly,
      'dgFixChargesMonthly': instance.dgFixChargesMonthly,
      'dgDrCrMonthly': instance.dgDrCrMonthly,
    };
